services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "${MAILPIT_EXPOSE_PORT}:1025"

  tolgee: # using minimum configuration
    image: tolgee/tolgee
    volumes:
      - ./data/tolgee:/data
    ports:
      - "${TOLGEE_EXPOSE_PORT}:8080"
    environment:
      tolgee.authentication.enabled: false
